export const localizations = {
	tr: {
		English: "İngilizce",
		Turkish: "Türkçe",
		Endless: "Sonsuz",
		Normal: "Normal",
		WordGame: "Kelime Oyunu",
		CountingGame: "Sayı Sayma Oyunu",
		anErrorOccured: "Bir hata oluştu, lütfen daha sonra tekrar deneyin.",
		buttonSetup: "Kur",
		buttonRemove: "Kaldır",
		buttonConfirm: "Onayla",
		confirmRemove: "Kaldırmayı Onayla",
		confirmRemoveDesc: "Oyunu kaldırmak için 15 saniyeniz var, oyunu kaldırmak istediğinize emin misiniz?",
		confirmRemoveExpire: "Onaylamak için süreniz doldu.",
        confirmUsed: "Bu onay mesajı artık geçersiz.",
		gameSetupSuccess: "Oyun başarıyla kuruldu!",
        gameRemoveSuccess: "Oyun başarıyla kaldırıldı.",
        gameWordCounter: "Yazılan Kelime",
        gameNumberCounter: "Yazılan Sayı",
        gameMultiplier: "Çarpan",
        gameMultiplierChange: (multiplier: string) => `Oyun çarpanı başarıyla **${multiplier}** yapıldı.`,
		gameMode: "Oyun Modu",
		gameModeNormalDesc: "Normal oyun modu, 40 kelimeden önce oyun bitirilemez",
		gameModeEndlessDesc: "Sonsuz oyun modu, oyun bitirilemez.",
		gameModeEndless: "Sonsuz",
		gameModeChange: (mode: string) => `Oyun modu başarıyla **${mode}** yapıldı.`,
		gameLocaleTr: "Türkçe",
		gameLocaleTrDesc: "Türkçe için oyun dili seçeneği.",
		gameLocaleEn: "İngilizce",
		gameLocaleEnDesc: "İngilizce için oyun dili seçeneği.",
		gameLocale: "Kanal Dili",
		gameLangChange: (lang: string) => `Oyun dili başarıyla **${lang}** yapıldı.`,
		gameExists: (gameType: string) => `Bu kanalda **${gameType}** kurulu.`,
		gameDoesntExists: "Bu kanalda oyun kurulu değil.",
        gameAnother: (game: string) => `Bu kanalda ${game} kurulu.`,
		commandTimeout: (command: string) => `Bu komut artık geçersiz, **/${command}** yazarak tekrar kullanabilirsiniz.`,
	},
	en: {
		English: "English",
		Turkish: "Turkish",
		Endless: "Endless",
		Normal: "Normal",
		WordGame: "Word Game",
		CountingGame: "Counting Game",
		anErrorOccured: "An error occured, please try again later.",
		buttonSetup: "Setup",
		buttonRemove: "Remove",
		buttonConfirm: "Confirm",
		confirmRemove: "Confirm Removal",
		confirmRemoveDesc: "You have 15 seconds to remove the game, are you sure you want to remove the game?",
		confirmRemoveExpire: "Your time has expired to confirm.",
        confirmUsed: "This confirmation message is expired.",
		gameSetupSuccess: "Game setup successfull!",
        gameRemoveSuccess: "Game removal successfull.",
        gameWordCounter: "Word Counter",
        gameNumberCounter: "Number Counter",
        gameMultiplier: "Multiplier",
        gameMultiplierChange: (multiplier: string) => `Game multiplier changed to: **${multiplier}**`,
		gameMode: "Game Mode",
		gameModeNormalDesc: "Normal game mode, game cannot be finished until 40 words.",
		gameModeEndlessDesc: "Endless game mode, game cannot be finished.",
		gameModeEndless: "Endless",
		gameModeChange: (mode: string) => `Game mode changed to: **${mode}**`,
		gameLocaleTr: "Turkish",
		gameLocaleTrDesc: "Game language option for Turkish.",
		gameLocaleEn: "English",
		gameLocaleEnDesc: "Game language option for English.",
		gameLocale: "Channel Language",
		gameLangChange: (lang: string) => `Game language changed to: **${lang}**`,
		gameExists: (gameType: string) => `There is a **${gameType}** in this channel.`,
		gameDoesntExists: "There is no game in this channel.",
        gameAnother: (game: string) => `There is ${game} in this channel.`,
		commandTimeout: (command: string) => `This command has expired, you can use it again by typing **/${command}**.`,
	},
};
